[pytest]
addopts = -s
markers =
    playwright: mark test as a Playwright end-to-end test

# Playwright specific settings
playwright_base_url = http://127.0.0.1:8001
playwright_headless = true
playwright_slow_mo = 100
