[build]
# Use Railway's Dockerfile builder and point it at our production Dockerfile
builder = "DOCKERFILE.PROD"


[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

