# Generated by Django 5.2.2 on 2026-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newspage_feature_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='news_location',
            field=models.CharField(blank=True, help_text='Location this news is about (e.g., Nairobi, Mombasa, Kenya)', max_length=255, null=True, verbose_name='Location'),
        ),
    ]
