# Generated by Django 5.2.2 on 2026-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_integrationsettings_track_internally'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='openweathermap_api_key',
            field=models.CharField(blank=True, help_text='Get a free API key at https://openweathermap.org/api', max_length=255, null=True, verbose_name='OpenWeatherMap API Key'),
        ),
    ]
